### ISSUE TITLE
Upgrade to latest version of the google github dependency

### ISSUE THREAD

**Issue by csykes** [RobotsAndPencils/marvin#17]
Looks like there is a breaking change in the latest version of the go-github dependency... so at some point we'll need to upgrade to the latest and patch all the breaks to continue development on Marvin

**Comment by nealsanche** [comment]
When running into this issue, you can also recover by typing:

```
$ godep restore
$ make clean
$ make run
```

Since the repo version of the go-github dependency works best at revision `2431923100d4989611dcc339f1ff8d280bd9c84c`. And `godep` knows how to restore the repositories to this version.

**Comment by MattKiazyk** [comment]
github-go has been updated in https://github.com/RobotsAndPencils/marvin/commit/f1aa0839164c510b67d3087d2aa62a2a34104820

to the latest

**Comment by paulthorsteinson** [comment]
Nothing appears to be broken!
