### ISSUE TITLE
Sort by duration when showing long running open PRs in Github

### ISSUE THREAD

**Issue by csykes** [RobotsAndPencils/marvin#20]
Change the sort order from Project/Duration to Duration/Project

**Comment by csykes** [comment]
<img width="582" alt="screen shot 2016-04-08 at 11 58 19 am" src="https://cloud.githubusercontent.com/assets/944809/14392914/3921a382-fd81-11e5-9a35-3d823e2de66a.png">

**Comment by paulthorsteinson** [comment]
Works as advertised!
