### ISSUE TITLE
BUG - Incorrectly reporting commits as being from master

### ISSUE THREAD

**Issue by aerickson14** [RobotsAndPencils/marvin#25]
When running the `/commitstomaster` command the output will, in some cases, report commits as being from master when in fact they are part of a valid Pull Request. 

If there is a Pull Request that was created exactly 7 days ago from the time the command was run but was run at an *earlier* time of day than the Pull Request was created then:
- Commits that are part of the PR could possibly be included in the list of candidate commits.

The current implementation of `/commitstomaster` does the following:
- Grabs a list of *all* `commits` in a repo (supposedly) where the commit date is within a 7 day time frame from the current time
- Grabs a list of `allPRCommits` that were created within the 7 day time frame.
- compares the list of `commits` to `allPRCommits` and returns anything leftover in the `allCommits` that was not part of `repoCommits`.

Possible problems:
- Investigate if `loadCommitsForRepo` returns commits that are *greater than* its `days` parameter
- Investigate if `loadCommitsFromAllRepoPRs` *does not include* commits that are within the `days` parameter.

**Comment by csykes** [comment]
I think it is because there are long running PRs that start before the reporting window. The code stop processing any more PRs once it discovers the first CreatedDate outside the reporting start date...

**Comment by aerickson14** [comment]
Yep, that sounds about right from what I observed. The hard part has been trying to retrieve the commits in a consistent way between loadCommitsForRepo and loadCommitsFromAllRepoPRs so that both return the full set of commits for the given time period.

**Comment by MattKiazyk** [comment]
@paulthorsteinson @aerickson14 i'll let you guys close this and QA it - it's up now to test

**Comment by paulthorsteinson** [comment]
Closing this up in favour of #29
