### ISSUE TITLE
/openpullrequests - Add in ability to provide a minimum open PR time to the command

### ISSUE THREAD

**Issue by csykes** [RobotsAndPencils/marvin#26]
How hard would it be so that i could pass a minimum time open param so like /openpullrequests 7 returns all prs open for 7 or more days (in projects that have been active in the last 30 days)?

Basically, this would add a second input command option for the open duration
`/openpullrequests 7 30`

In addition, we should modify the messaging to be more clear from:
`Calculating open pull requests that have been open for more than 1 day...`

To something like:
`Finding pull requests that are still open after 7 days in projects that have been active in the last 30 days`

**Comment by paulthorsteinson** [comment]
works as advertised
